/**
 * Conversation types for AMU Platform
 * Based on Sections 5.1.8 and 5.1.9 of the specification
 */

import type { CompetencyStatus } from './enrolment';

export type ConversationType = 'inquiry' | 'learning' | 'assessment';
export type ConversationStatus = 'active' | 'paused' | 'completed';
export type MessageRole = 'user' | 'assistant';

export interface CompetencyAssessment {
  competency_id: string;
  assessment_result: CompetencyStatus;
  evidence_captured: string;
}

export interface Message {
  message_id: string;
  message_role: MessageRole;
  message_content: string;
  message_timestamp: Date;

  // Token tracking
  message_input_tokens?: number;
  message_output_tokens?: number;

  // Assessment (if this message contains assessment)
  message_competency_assessment?: CompetencyAssessment;
}

export interface Conversation {
  conversation_id: string;
  conversation_user_id: string;
  conversation_enrolment_id?: string;
  conversation_type: ConversationType;

  // Status
  conversation_status: ConversationStatus;
  conversation_started_date: Date;
  conversation_last_message_date: Date;

  // Context
  conversation_module_id?: string;
  conversation_competency_id?: string;

  // Stats
  conversation_message_count: number;
  conversation_total_tokens_used: number;

  // Summaries
  conversation_latest_summary_id?: string;
  conversation_summary_count: number;
}

export interface ConversationSummary {
  summary_id: string;
  summary_conversation_id: string;
  summary_session_number: number;

  // Message Range
  summary_start_message_id: string;
  summary_end_message_id: string;
  summary_message_count: number;

  // Content (generated by Claude)
  summary_text: string;
  summary_key_insights: string[];
  summary_breakthroughs: string[];
  summary_struggles: string[];
  summary_notable_moments: string[];

  // Metadata
  summary_created_date: Date;
  summary_tokens_used: number;
}

/**
 * Conversation document for Firestore (with serialized dates)
 */
export interface ConversationDocument extends Omit<Conversation, 'conversation_started_date' | 'conversation_last_message_date'> {
  conversation_started_date: string;
  conversation_last_message_date: string;
}

/**
 * Message document for Firestore (with serialized dates)
 */
export interface MessageDocument extends Omit<Message, 'message_timestamp'> {
  message_timestamp: string;
}

/**
 * Summary document for Firestore (with serialized dates)
 */
export interface ConversationSummaryDocument extends Omit<ConversationSummary, 'summary_created_date'> {
  summary_created_date: string;
}

/**
 * Create conversation input
 */
export interface CreateConversationInput {
  conversation_user_id: string;
  conversation_enrolment_id?: string;
  conversation_type: ConversationType;
  conversation_module_id?: string;
  conversation_competency_id?: string;
}

/**
 * Send message input
 */
export interface SendMessageInput {
  conversation_id: string;
  content: string;
}
